# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0203ba77f9c39fbe8a6ad65dbbb6302e2d8163788d343f71ba722c1e640b2ac3ff3cfaeb342f45ed0ba7d453b7c4b223859e0cbd8393aab225ac20499079f603

test:
  secret_key_base: 50f298a036213c65f7ea5999bf2218450d46ac30aeadb1aac7e769b6ef33895a1c71e4d1a6f1dbcd0d9dde29baa7e0578a4dd27135a6be4d5cb84c4303c8c446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
